# Generated by Django 3.1.1 on 2020-10-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
