# Generated by Django 3.1.1 on 2020-11-05 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_uservolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservolunteer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
