# Generated by Django 3.1.1 on 2020-11-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user',
            new_name='creator',
        ),
    ]
