# Generated by Django 3.1.1 on 2020-10-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20201022_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
    ]
