# Generated by Django 3.1.1 on 2020-10-20 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20201019_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
