# Generated by Django 3.1.1 on 2020-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20201105_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
