# Generated by Django 3.1.1 on 2020-10-22 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_volunteerpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerpost',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
