# Generated by Django 3.1.1 on 2020-10-22 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_volunteerpost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
