# Generated by Django 3.1.1 on 2020-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20201105_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
