# Generated by Django 3.1.1 on 2020-11-02 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0005_auto_20201101_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to=settings.AUTH_USER_MODEL),
        ),
    ]
