# Generated by Django 3.1.1 on 2020-11-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0006_auto_20201101_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.CreateModel(
            name='UserDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('goal', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
