# Generated by Django 3.1.1 on 2020-10-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20201021_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerpost',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerpost',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
