# Generated by Django 3.1.1 on 2020-11-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20201103_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
